// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/c17b1b78b886e84afe27e1b65fe5bf901da5bbe7/deep-freeze/index.d.ts
declare module 'deep-freeze' {
// Type definitions for deep-freeze
// Project: https://github.com/substack/deep-freeze
// Definitions by: Bart van der Schoor <https://github.com/Bartvds>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

var deepFreeze: DeepFreeze.DeepFreezeInterface;
export = deepFreeze;

namespace DeepFreeze {
   export interface DeepFreezeInterface {
      <T>(obj: T): T;
    }
}
}
